# Generated by Django 3.1.2 on 2020-10-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowbook',
            old_name='book_id',
            new_name='book',
        ),
    ]
